# Generated by Django 2.2 on 2020-04-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('review', models.TextField()),
            ],
        ),
    ]
